management_system/dealer_app/urls.py
from django.contrib import admin
from django.urls import path,include
from dealer_app import views

urlpatterns = [
 
    path('dealer_detail/',views.dealer),
    path('dealer_form/',views.dealer_form),
    path('distributer_form/',views.Distributers),
    path('distributer_detail/',views.distributer_object),
    path('dealer_delete/<int:id>/',views.delete_data),
    path('dealer_update/<int:id>/',views.update_data),
    path('distributer_delete/<int:id>/',views.Distributer_delete_data),
    path('distributer_update/<int:id>/',views.Distributer_update_data),

]

management_system/management_system/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

from management_system import views, admin_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('base/', views.BASE, name='base'),

    # login path
    path('', include('authentication_app.urls'), name='login'),
    # path('doLogin', views.doLogin, name='doLogin'),

    # logout path
    # path('doLogout', views.doLogout, name='logout'),


    # signup



    # profile update
    path('Profile', views.PROFILE, name='profile'),
    path('Profile/update', views.PROFILE_UPDATE, name='profile_update'),


    # Admin Panel addd

    path('Admin/Home', admin_views.HOME, name='admin_home'),
    path('Admin/Farmer/Add', admin_views.ADD_FARMER, name="add_farmer"),
    path('Admin/Distributor/Add',admin_views.ADD_DISTRIBUTOR, name="add_distributor"),
    path('Admin/Dealer/Add', admin_views.ADD_DEALER, name="add_dealer"),


    path('Admin/Employee/View',admin_views.VIEW_EMPLOYEE, name="view_employee"),
    path('Admin/Farmer/View',admin_views.VIEW_FARMER, name="view_farmer"),
    path('Admin/Dealer/View',admin_views.VIEW_DEALER, name="view_dealer"),
    path('Admin/Distributor/View',admin_views.VIEW_DISTRIBUTOR, name="view_distributor"),
    path('Admin/Resources', admin_views.RESOURCES, name='resources'),



    # main dealer distributer farmer url
    path('Admin/deal/',include('dealer_app.urls')),
    path('Admin/farm/',include('farmer_app.urls')),
    path('Admin/emp/',include('employee_app.urls')),


    path('Admin/auth/',include('authentication_app.urls')),
    
    
   

   
    
       
    #employee panel


    path('search/',admin_views.search),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


management_system/employee_app/models.py
from django.db import models
# from app.models import CustomUser

# Create your models here.


class Employee_model(models.Model):

    # admin = models.OneToOneField(CustomUser, on_delete=models.CASCADE)

    GENDER = (

        ('male', 'male'),
        ('female', 'female'),
        ('other', 'other'),
    )

    DEEIGNATION = (

        ('Sales Officer', 'Sales Officer'),
        ('Territory Exceutive', 'Territory Exceutive'),
        ('Field Assistant', 'Field Assistant'),
        ('General Manager', 'General Manager'),
        ('HR Manager', 'HR Manager'),
        ('Office Management Staff', 'Office Management Staff'),
        ('CA', 'CA'),
        ('Director', 'Director'),
        ('Desk Office Assitant', 'Desk Office Assitant'),


    )
    profile_pic = models.ImageField(upload_to='media/profile_pic')
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    mobile_no = models.IntegerField(null=True, blank=True)
    gender = models.CharField(choices=GENDER, max_length=100)
    designation = models.CharField(choices= DEEIGNATION, max_length=100)
    email = models.EmailField(max_length=100)
    address = models.TextField()
    pan_card = models.ImageField(upload_to='media/pan_card')
    adhar_card = models.ImageField(upload_to='media/adhar_card')
    cheque = models.ImageField(upload_to='media/bank_details')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

management_system/templates/employee/home.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
    <div class="col-sm-12">
    <div class="card">
    <div class="card-body">
    <form method="POST" action="/Admin/emp/employee_add/" enctype="multipart/form-data">
        {% csrf_token %}
    <div class="col-12">
    <h5 class="form-title"><span>Add Employee</span></h5>
    </div>
        {% if messages %}
        {% for message in messages %}
        {% if message.tags == 'error' %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                {{message}}
    
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endif %}
        {% endfor %}
        {% endif %}
    
        {% if messages %}
        {% for message in messages %}
        {% if message.tags == 'success' %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                {{message}}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endif %}
        {% endfor %}
        {% endif %}
   


        {% for i in a %}

        <div class="form-group">
           
            {{i.label_tag}}  {{i}}  {{i.error | striptags}}
    
        </div>

        {% endfor %}

    <div class="col-12">
    <button type="submit" class="btn btn-primary">Add Employee</button>
    </div>
        <br>
    
    </div>
    </form>
    </div>
    </div>
    </div>
    {% endblock %}

management_system/templates/employee/update_employee.html
{% extends 'base.html' %}
{% block content %}


{% for i in data %}

<form method="POST" action="/Admin/emp/employee_update/{{i.id}}/" enctype="multipart/form-data">
    {% csrf_token %}
<div class="col-12">
<h5 class="form-title"><span>Update Employee Details</span></h5>
</div>
    

    


 
    

    <div class="form-group">
       
        <label for="id_profile_pic">Profile pic:</label>  <input type="file" name="profile_pic" class="form-control" accept="image/*"  value = {{i.profile_pic}}>  

    </div>

    

    <div class="form-group">
       
        <label for="id_first_name">First name:</label>  <input type="text" name="first_name" class="form-control" maxlength="100" required id="id_first_name"  value = {{i.first_name}}>  

    </div>

    

    <div class="form-group">
       
        <label for="id_last_name">Last name:</label>  <input type="text" name="last_name" class="form-control" maxlength="100" required id="id_last_name"  value = {{i.last_name}}>  

    </div>

    

    <div class="form-group">
       
        <label for="id_mobile_no">Mobile no:</label>  <input type="number" name="mobile_no" class="form-control" id="id_mobile_no"  value = {{i.mobile_no}}>  

    </div>

    

    <div class="form-group">
       
        <label for="id_gender">Gender:</label>
        {{gender}}

 

    </div>

    

    <div class="form-group">
       
       <label for="id_designation">Designation:</label>  
         {{d}}

 

    </div>

    

    <div class="form-group">
       
        <label for="id_email">Email:</label>  <input type="email" name="email" class="form-control" maxlength="100" required id="id_email"  value = {{i.email}}>  

    </div>

    

    <div class="form-group">
       
        <label for="id_address">Address:</label>  <textarea name="address" cols="40" rows="10" class="form-control" required id="id_address"  value = {{i.address}}>
</textarea>  

    </div>

    

    <div class="form-group">
       
        <label for="id_pan_card">Pan card:</label>  <input type="file" name="pan_card" class="form-control" accept="image/*" required id="id_pan_card"  value = {{i.pan_card}}>  

    </div>

    

    <div class="form-group">
       
        <label for="id_adhar_card">Adhar card:</label>  <input type="file" name="adhar_card" class="form-control" accept="image/*" required id="id_adhar_card"  value = {{i.adhar_card}}>  

    </div>

    

    <div class="form-group">
       
        <label for="id_cheque">Cheque:</label>  <input type="file" name="cheque" class="form-control" accept="image/*" required id="id_cheque"  value = {{i.cheque}}>  

    </div>

    

<div class="col-12">
<button type="submit" class="btn btn-primary">Update Employee</button>
</div>
    <br>


{% endfor %}

{% endblock %}

management_system/templates/employee/view_employee.html
{% extends 'base.html' %}
{% block content %}
  <div class="content container-fluid">
    <div class="page-header">
      <div class="row align-items-center">
        <div class="col">
          <h3 class="page-title">Employee</h3>
          <ul class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="/Admin/Home">Dashboard</a>
            </li>
            <li class="breadcrumb-item active">Employee</li>
          </ul>
        </div>
        <div class="col-auto text-right float-right ml-auto">
          {% comment %} <a href="#" class="btn btn-outline-primary mr-2"><i class="fas fa-download"></i> Download</a> {% endcomment %}
          <a href="/Admin/emp/employee_add/" class="btn btn-primary">Add <i class="fas fa-plus"></i></a>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-12">
        <div class="card card-table">
          <div class="card-body">
            <div class="table-responsive">
              <table id="table_id" class="table table-hover table-center mb-0">
                <thead>
                  <tr>
                    <th>User Profile</th>
                    <th>First Name</th>
                  
                    <th>Mobile No</th>
                    <th>Gender</th>
                    <th>Designation</th>
                    <th>Email</th>
                    <th>Address</th>
                    <th>Pan Card</th>
                    <th>Adhar Card</th>
                    <th>Cheque</th>

                    <th class="text-right">Action</th>
                  </tr>
                </thead>
                <tbody>
                  {% for i in data %}
                    <tr>
                      <td>
                        <h2 class="table-avatar">
                          <a href="student-details.html" class="avatar avatar-sm mr-2"><img class="avatar-img rounded-circle" src="/media/{{ i.profile_pic }}" alt="User Image" width="100%" height="100%" /></a>
                          {% comment %} <a href="student-details.html">{{ i.first_name }}</a> {% endcomment %}
                        </h2>
                      </td>
                      <td>{{ i.first_name }}</td>
                      <td>{{ i.mobile_no }}</td>
                      <td>{{ i.gender }}</td>
                      <td>{{ i.designation }}</td>
                      <td>{{ i.email }}</td>
                      <td>{{ i.address }}</td>
                      <td>
                        <img src="/media/{{ i.pan_card }}" alt="" width = "100%"  height = "100%"/>
                      </td>
                      <td>
                        <img src="/media/{{ i.adhar_card }} " alt="" width = "100%"  height = "100%"/>
                      </td>
                      <td>
                        <img src="/media/{{ i.cheque }}" alt="" width = "100%"  height = "100%"/>
                      </td>

                      <td class="text-right">
                        <div class="actions">
                          <a href="/Admin/emp/employee_update/{{i.id}}/" class="btn btn-sm bg-success-light mr-2"><i class="fas fa-pen"></i></a>
                          <a href="/Admin/emp/employee_delete/{{i.id}}/" class="btn btn-sm bg-danger-light"><i class="fas fa-trash"></i></a>
                        </div>
                      </td>
                    </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}